R1:
  hostname: '192.168.0.100'
  port: 22
  username: 'admin'
  password: 'admin'
  platform: 'ios'
R2:
  hostname: '192.168.0.101'
  port: 22
  username: 'admin'
  password: 'admin'
  platform: 'ios'
R3:
  hostname: '192.168.0.102'
  port: 22
  username: 'admin'
  password: 'admin'
  platform: 'ios'
R4:
  hostname: '192.168.0.103'
  port: 22
  username: 'admin'
  password: 'admin'
  platform: 'ios'
R5:
  hostname: '192.168.0.104'
  port: 22
  username: 'admin'
  password: 'admin'
  platform: 'ios'
